# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

os:
  - linux
  - osx

sudo: false

cache: packages

before_install:
  - R -e 'install.packages("devtools")'
  - tlmgr install index
  - R -e 'devtools::install_github("Bioconductor/BiocGenerics")'
  - R -e 'devtools::install_github("RGLab/openCyto", ref = "trunk")'
  
install:
  - R -e 'devtools::install_deps(dep = T, type = "source")'

warnings_are_errors: false