# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

os:
  - linux
  - osx

sudo: false

cache: packages

before_install:
  - R -e 'install.packages("devtools")'
  - tlmgr install index
  
install:
  - R -e 'devtools::install_deps(dep = T, type = "source")'

warnings_are_errors: false

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'