#' Add boxed text labels to cyto_plot
#'
#' @param x object of class \code{"flowFrame"}.
#' @param gates object of class
#'   \code{\link[flowCore:rectangleGate-class]{rectangleGate}},
#'   \code{\link[flowCore:polygonGate-class]{polygonGate}},
#'   \code{\link[flowCore:ellipsoidGate-class]{ellipsoidGate}}, \code{"list"} or
#'   \code{\link[flowCore:filters-class]{filters}}.
#' @param ... additional method-specific arguments.
#'
#' @return add a boxed text label to cyto_plot.
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @importFrom flowCore Subset parameters
#'
#' @seealso \code{\link{cyto_plot_label,flowFrame,rectangleGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,polygonGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,ellipsoidGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,list-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,filters-method}}
#'
#' @export
setGeneric(
  name = "cyto_plot_label",
  def = function(x, gates, ...) {
    standardGeneric("cyto_plot_label")
  }
)

#' Add boxed text labels to cyto_plot without gate
#'
#' \code{cyto_plot_label} takes on a \code{flowFrame} object, population name
#' \code{text}, \code{channels} and a gate object to construct a text label for
#' the plot with the population name and frequency. In the absence of a gate,
#' users can manually specify the label position using the \code{text_x} and
#' \code{text_y} arguments.
#'
#' @param x a \code{\link[flowCore:flowFrame-class]{flowFrame}} gated in the
#'   existing plot.
#' @param gates \code{NULL}.
#' @param trans object of class
#'   \code{\link[flowCore:transformList-class]{transformList}} or
#'   \code{\link[flowWorkspace]{transformerList}} generated by
#'   \code{\link[flowCore:logicleTransform]{estimateLogicle}} which was used to
#'   transform the fluorescent channels of the supplied flowFrame.
#' @param channels a vector indicating the fluorescent channel(s) to be used for
#'   gating.
#' @param text character string to include in the label above the statistic
#'   (e.g. population name(s)).
#' @param stat indicates the type of statistic to include in the label, can be
#'   either code{"count"}, \code{"median"}, \code{"mean"}, \code{"mode"} or
#'   \code{"geo mean"}. \code{stat} is set to \code{"median"} by default.
#'   Statistics for fluorescent intensity are calculated for the entire
#'   distribution. Only count and percent statistics are supported for 2D
#'   plots.
#' @param text_x vector containing the x co-ordiantes for the plot labels. Set
#'   to \code{NULL} by default to place labels in the center of the gates.
#' @param text_y vector containing the x co-ordiantes for the plot labels. Set
#'   to \code{NULL} by default to place labels in the center of the gates.
#' @param text_font integer [1,2,3,4] passed to \code{text} to alter the font,
#'   set to \code{2} by default for a bold font.
#' @param text_size numeric character expansion used to control the size of the
#'   text in the labels, set to \code{0.8} by default. See \code{?text} for
#'   details.
#' @param text_col specify text colour in label for each gate, defaults to
#'   \code{"black"} for all gates.
#' @param box_alpha numeric [0,1] controls the transparency of the background,
#'   set to \code{0.6} by default.
#' @param adjust smoothing parameter passed to
#'   \code{\link[stats:density]{density}} to adjust kernel density for mode
#'   calculation.
#'
#' @return add a boxed text label to cyto_plot.
#'
#' @importFrom flowCore Subset parameters
#' @importFrom graphics par
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @seealso \code{\link{cyto_plot_label,flowFrame,polygonGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,ellipsoidGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,list-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,filters-method}}
#'
#' @export
setMethod(cyto_plot_label,
          signature = c("flowFrame", NULL),
          definition = function(x, 
                                gates = NULL,
                                trans = NULL,
                                channels, 
                                text = NA, 
                                stat = NA,
                                text_x = NA, 
                                text_y = NA, 
                                text_font = 2, 
                                text_size = 0.8, 
                                text_col = "black", 
                                box_alpha = 0.6,
                                adjust = 1.5) {
            
  # Assign x to fr
  fr <- x
            
  # Channels needed to position label
  if (missing(channels)) {
    stop("Supply the name(s) of the fluorescent channels used to construct the plot.")
  }
  
  # Missing transList
  if(stat %in% c("median","mode","mean","geo mean")){
    if(is.null(checkTransList(trans))){
      stop("Supply the transform object used to transform the fluorescent channels of the flowFrame.")
    }
  }
     
  # Stats not supported in 2D
  if(length(channels) == 2 & stat %in% c("mean","median","mode","geo mean")){
    stop("Only count is supported for 2D plots without gates.")
  }
         
  # Missing text
  if (is.na(text) & !is.na(stat)) {
    message(paste("No text supplied for labels - labels will show", stat, "only."))
  }
         
  # Calculate statistics
  if(stat == "count"){
    
    st <- BiocGenerics::nrow(fr)
    
  }else if(stat == "median"){
    
    fr <- .getRawData(x = fr, transList = trans)
    st <- median(flowCore::exprs(fr)[,channels])
    st <- round(st, 2)
    
  }else if(stat == "mean"){
    
    fr <- .getRawData(x = fr, transList = trans)
    st <- mean(flowCore::exprs(fr)[,channels])
    st <- round(st, 2)
    
  }else if(stat == "mode"){
    
    fr <- .getRawData(x = fr, transList = trans)
    d <- density(flowCore::exprs(fr)[,channels], adjust = adjust)
    st <- d$x[d$y == max(d$y)]
    st <- round(st, 2)
    
  }else if(stat == "geo mean"){
    
    st <- mean(flowCore::exprs(fr)[,channels])
    inv <- checkTransList(trans, inverse = TRUE)
    st <- inv@transforms[[channels]]@f(st)
    st <- round(st, 2)
    
  }
      
  # Plot Limits
  xmin <- par("usr")[1]
  xmax <- par("usr")[2]
  ymin <- par("usr")[3]
  ymax <- par("usr")[4]
        
  # Label position
  if (is.na(text_x) & is.na(text_y)) {
    text_x <- (xmin + xmax) / 2
    text_y <- (ymin + ymax) / 2
  }else if(!is.na(text_x) & is.na(text_y)){
    text_y <- (ymin + ymax)/2
  }else if(is.na(text_x) & !is.na(text_y)){
    text_x <- xmin + (xmax - xmin)*0.75
  }
            
  # Add labels
  if(!is.na(text) & !is.na(stat)){
    boxed.labels(x = text_x, y = text_y, labels = paste(text, st, sep = "\n"), border = FALSE, font = text_font, col = text_col, alpha.bg = box_alpha, cex = text_size)
  }else if(!is.na(text) & is.na(stat)){
    boxed.labels(x = text_x, y = text_y, labels = text, border = FALSE, font = text_font, col = text_col, alpha.bg = box_alpha, cex = text_size)
  }else if(is.na(text) & !is.na(stat)){
    boxed.labels(x = text_x, y = text_y, labels = st, border = FALSE, font = text_font, col = text_col, alpha.bg = box_alpha, cex = text_size)
  }
  
})

#' Add boxed text labels to cyto_plot - rectangleGate Method
#'
#' \code{cyto_plot_label} takes on a \code{flowFrame} object, population name
#' \code{text}, \code{channels} and a gate object to construct a text label for
#' the plot with the population name and frequency.
#'
#' @param x a \code{\link[flowCore:flowFrame-class]{flowFrame}} gated in the
#'   existing plot.
#' @param gates an object of class
#'   \code{\link[flowCore:rectangleGate-class]{rectangleGate}}.
#' @param trans object of class
#'   \code{\link[flowCore:transformList-class]{transformList}} or
#'   \code{\link[flowWorkspace]{transformerList}} generated by
#'   \code{\link[flowCore:logicleTransform]{estimateLogicle}} which was used to
#'   transform the fluorescent channels of the supplied flowFrame.
#' @param channels a vector indicating the fluorescent channel(s) to be used for
#'   gating.
#' @param text character string to include in the label above the statistic
#'   (e.g. population name(s)).
#' @param stat indicates the type of statistic to include in the label, can be
#'   either \code{"percent"}, \code{"count"}, \code{"median"}, \code{"mean"},
#'   \code{"mode"} or \code{"geo mean"}. \code{stat} is set to \code{"percent"}
#'   by default. Statistics for fluorescent intensity are calculated for the
#'   entire distribution. Only count and percent statistics are supported for 2D
#'   plots.
#' @param text_x vector containing the x co-ordiantes for the plot labels. Set
#'   to \code{NULL} by default to place labels in the center of the gates.
#' @param text_y vector containing the x co-ordiantes for the plot labels. Set
#'   to \code{NULL} by default to place labels in the center of the gates.
#' @param text_font integer [1,2,3,4] passed to \code{text} to alter the font,
#'   set to \code{2} by default for a bold font.
#' @param text_size numeric character expansion used to control the size of the
#'   text in the labels, set to \code{0.8} by default. See \code{?text} for
#'   details.
#' @param text_col specify text colour in label for each gate, defaults to
#'   \code{"black"} for all gates.
#' @param box_alpha numeric [0,1] controls the transparency of the background,
#'   set to \code{0.6} by default.
#' @param adjust smoothing parameter passed to
#'   \code{\link[stats:density]{density}} to adjust kernel density for mode
#'   calculation.
#'
#' @return add a boxed text label to cyto_plot.
#'
#' @importFrom flowCore Subset parameters
#' @importFrom graphics par
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @seealso \code{\link{cyto_plot_label,flowFrame,polygonGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,ellipsoidGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,list-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,filters-method}}
#'
#' @export
setMethod(cyto_plot_label,
  signature = c("flowFrame", "rectangleGate"),
  definition = function(x, 
                        gates = NULL,
                        trans = NULL,
                        channels, 
                        text = NA, 
                        stat = NA, 
                        text_x = NA, 
                        text_y = NA, 
                        text_font = 2, 
                        text_size = 0.8, 
                        text_col = "black", 
                        box_alpha = 0.6, 
                        adjust = 1.5) {

    # Assign x to fr
    fr <- x

    # Channels needed to position label
    if (missing(channels)) {
      stop("Supply the name(s) of the fluorescent channels used to construct the plot.")
    }

    # Only count and percent supported in 2D
    if(length(channels) == 2 & !stat %in% c("count","percent")){
      stop("Only count and percent statistics are supported in 2D plots.")
    }
    
    # Missing transList
    if(stat %in% c("median","mode","mean","geo mean")){
      if(is.null(checkTransList(trans))){
        stop("Supply the transform object used to transform the fluorescent channels of the flowFrame.")
      }
    }
    
    # 2D gate in 1D plot
    if (length(channels) == 1 & length(parameters(gates)) == 2) {
      gates <- gates[channels]
    }

    # Missing text
    if (is.na(text) & !is.na(stat)) {
      message(paste("No text supplied for labels - labels will show", stat, "only."))
    }

    # Calculate statistics
    if(stat == "count"){
      
      st <- BiocGenerics::nrow(flowCore::Subset(fr, gates))
      
    }else if(stat == "percent"){
      
      # Total events
      events <- BiocGenerics::nrow(fr)

      # Population events - percentages
      cnt <- BiocGenerics::nrow(flowCore::Subset(fr, gates))
      prcnt <- round(cnt / events, 4)
      st <- sprintf("%.2f %%", 100 * prcnt)
      
    }else if(stat == "mean"){
      
      fr <- .getRawData(x = fr, transList = trans)
      st <- mean(flowCore::exprs(fr)[,channels])
      
    }else if(stat == "median"){
      
      fr <- .getRawData(x = fr, transList = trans)
      st <- median(flowCore::exprs(fr)[,channels])
      st <- round(st, 2)
      
    }else if(stat == "mode"){
      
      fr <- .getRawData(x = fr, transList = trans)
      d <- density(flowCore::exprs(fr)[,channels], adjust = adjust)
      st <- d$x[d$y == max(d$y)]
      st <- round(st, 2)
      
    }else if(stat == "geo mean"){
      
      st <- mean(flowCore::exprs(fr)[,channels])
      inv <- checkTransList(trans, inverse = TRUE)
      st <- inv@transforms[[channels]]@f(st)
      st <- round(st, 2)
      
    }

    # 1D gate plotted in 2D
    if (length(channels) == 2 & length(parameters(gates)) == 1) {
      rg <- matrix(c(as.numeric(gates@min), as.numeric(gates@max), -Inf, Inf), ncol = 2, nrow = 2)
      colnames(rg) <- c(as.vector(parameters(gates)), channels[!channels == as.vector(parameters(gates))])
      rownames(rg) <- c("min", "max")
      gates <- rectangleGate(.gate = rg)
    }

    # Gate channels
    chans <- as.vector(parameters(gates))

    # 1D gate supplied
    if (length(chans) == 1) {
      if (length(channels) == 1) {
        if (!channels == chans) {
          stop("Supplied channel does not match that of the supplied gate.")
        } else if (channels == chans) {
          if (is.na(text_x) & is.na(text_y)) {
            xmin <- gates@min
            xmax <- gates@max

            if (is.infinite(xmin)) {
              xmin <- par("usr")[1]
            }

            if (is.infinite(xmax)) {
              xmax <- par("usr")[2]
            }

            ymin <- par("usr")[3]
            ymax <- par("usr")[4]
          }
        }
      } else if (length(channels) == 2) {
        if (!chans %in% channels) {
          stop("Supplied channels do not match that of the supplied gate.")
        } else if (chans %in% channels) {
          if (is.na(text_x) & is.na(text_y)) {
            ind <- match(chans, channels)

            if (ind == 1) {
              xmin <- gates@min[channels[1]]
              xmax <- gates@max[channels[1]]

              if (is.infinite(xmin)) {
                xmin <- par("usr")[1]
              }

              if (is.infinite(xmax)) {
                xmax <- par("usr")[2]
              }

              ymin <- par("usr")[3]
              ymax <- par("usr")[4]
            } else if (ind == 2) {
              ymin <- gates@min[channels[2]]
              ymax <- gates@max[channels[2]]

              if (is.infinite(xmin)) {
                ymin <- par("usr")[3]
              }

              if (is.infinite(xmax)) {
                ymax <- par("usr")[4]
              }

              xmin <- par("usr")[1]
              xmax <- par("usr")[2]
            }
          }
        }
      }

      # 2D gate supplied
    } else if (length(chans) == 2) {
      if (!all(chans %in% channels)) {
        stop("Supplied channels do not match that of the supplied gate.")
      } else if (all(chans %in% channels)) {
        if (is.na(text_x) & is.na(text_y)) {
          xmin <- gates@min[channels[1]]
          ymin <- gates@min[channels[2]]
          xmax <- gates@max[channels[1]]
          ymax <- gates@max[channels[2]]

          if (is.infinite(xmin)) {
            xmin <- par("usr")[1]
          }

          if (is.infinite(ymin)) {
            ymin <- par("usr")[3]
          }

          if (is.infinite(xmax)) {
            xmax <- par("usr")[2]
          }

          if (is.infinite(ymax)) {
            ymax <- par("usr")[4]
          }
        }
      }
    }

    # Label position
    if (is.na(text_x) & is.na(text_y)) {
      text_x <- (xmin + xmax) / 2
      text_y <- (ymin + ymax) / 2
    }

    # Add labels
    if(!is.na(text) & !is.na(stat)){
      boxed.labels(x = text_x, y = text_y, labels = paste(text, st, sep = "\n"), border = FALSE, font = text_font, col = text_col, alpha.bg = box_alpha, cex = text_size)
    }else if(!is.na(text) & is.na(stat)){
      boxed.labels(x = text_x, y = text_y, labels = text, border = FALSE, font = text_font, col = text_col, alpha.bg = box_alpha, cex = text_size)
    }else if(is.na(text) & !is.na(stat)){
      boxed.labels(x = text_x, y = text_y, labels = st, border = FALSE, font = text_font, col = text_col, alpha.bg = box_alpha, cex = text_size)
    }
    
  }
)

#' Add boxed text labels to cyto_plot - polygonGate Method
#'
#' \code{cyto_plot_label} takes on a \code{flowFrame} object, population name
#' \code{text}, \code{channels} and a gate object to construct a text label for
#' the plot with the population name and frequency.
#'
#' @param x a \code{\link[flowCore:flowFrame-class]{flowFrame}} gated in the
#'   existing plot.
#' @param gates an object of class
#'   \code{\link[flowCore:polygonGate-class]{polygonGate}}.
#' @param channels a vector indicating the fluorescent channel(s) to be used for
#'   gating.
#' @param text the name of the gated population, set to NA by default to only
#'   include percent in labels.
#' @param stat indicates the type of statistic to include in the label, can be
#'   either \code{"percent"} or \code{"count"}. \code{stat} is set to
#'   \code{"percent"} by default.
#' @param text_x vector containing the x co-ordiantes for the plot labels. Set
#'   to \code{NULL} by default to place labels in the center of the gates.
#' @param text_y vector containing the x co-ordiantes for the plot labels. Set
#'   to \code{NULL} by default to place labels in the center of the gates.
#' @param text_font integer [1,2,3,4] passed to \code{text} to alter the font,
#'   set to \code{2} by default for a bold font.
#' @param text_size numeric character expansion used to control the size of the
#'   text in the labels, set to \code{0.8} by default. See \code{?text} for
#'   details.
#' @param text_col specify text colour in label for each gate, defaults to
#'   \code{"black"} for all gates.
#' @param box_alpha numeric [0,1] controls the transparency of the background,
#'   set to \code{0.6} by default.
#'
#' @return add a boxed text label to cyto_plot.
#'
#' @importFrom flowCore Subset parameters
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @seealso \code{\link{cyto_plot_label,flowFrame,rectangleGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,ellipsoidGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,list-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,filters-method}}
#'
#' @export
setMethod(cyto_plot_label,
  signature = c("flowFrame", "polygonGate"),
  definition = function(x, 
                        gates, 
                        channels, 
                        text = NA, 
                        stat = NA, 
                        text_x = NA, 
                        text_y = NA, 
                        text_font = 2, 
                        text_size = 0.8, 
                        text_col = "black", 
                        box_alpha = 0.6) {

    # Assign x to fr
    fr <- x

    # Channels needed to position label
    if (missing(channels)) {
      stop("Supply the name(s) of the fluorescent channels used to construct the plot.")
    }

    # Only count and percent supported
    if(!stat %in% c("count","percent")){
      stop("Only count and percent statistics are supported for 2D plots containing a polygonGate.")
    }
    
    # Missing text
    if (is.na(text) & !is.na(stat)) {
      message(paste("No text supplied for labels - labels will show", stat, "only."))
    }

    # Calculate statistic
    if(stat == "count"){
      st <- BiocGenerics::nrow(flowCore::Subset(fr, gates))
    }else if(stat == "percent"){
      # Total events
      events <- nrow(fr)
      
      # Population events - percentages
      cnt <- BiocGenerics::nrow(flowCore::Subset(fr, gates))
      prcnt <- round(cnt / events, 4)
      st <- sprintf("%.2f %%", 100 * prcnt)
    }

    # Check supplied channels & gate channels
    chans <- parameters(gates)

    if (!all(chans %in% channels)) {
      stop("Supplied channels do not match that of the supplied gate.")
    } else {
      if (is.na(text_x) & is.na(text_y)) {
        text_x <- sum(gates@boundaries[, channels[1]]) / nrow(gates@boundaries)
        text_y <- sum(gates@boundaries[, channels[2]]) / nrow(gates@boundaries)
      }
    }

    # Add labels
    if(!is.na(text) & !is.na(stat)){
      boxed.labels(x = text_x, y = text_y, labels = paste(text, st, sep = "\n"), border = FALSE, font = text_font, col = text_col, alpha.bg = box_alpha, cex = text_size)
    }else if(!is.na(text) & is.na(stat)){
      boxed.labels(x = text_x, y = text_y, labels = text, border = FALSE, font = text_font, col = text_col, alpha.bg = box_alpha, cex = text_size)
    }else if(is.na(text) & !is.na(stat)){
      boxed.labels(x = text_x, y = text_y, labels = st, border = FALSE, font = text_font, col = text_col, alpha.bg = box_alpha, cex = text_size)
    }
    
  }
)

#' Add boxed text labels to cyto_plot - ellipsoidGate Method
#'
#' \code{cyto_plot_label} takes on a \code{flowFrame} object, population name
#' \code{text}, \code{channels} and a gate object to construct a text label for
#' the plot with the population name and frequency.
#'
#' @param x a \code{\link[flowCore:flowFrame-class]{flowFrame}} gated in the
#'   existing plot.
#' @param gates an object of class
#'   \code{\link[flowCore:ellipsoidGate-class]{ellipsoidGate}}.
#' @param channels a vector indicating the fluorescent channel(s) to be used for
#'   gating.
#' @param text the name of the gated population, set to NA by default to only
#'   include percent in labels.
#' @param stat indicates the type of statistic to include in the label, can be
#'   either \code{"percent"} or \code{"count"}. \code{stat} is set to
#'   \code{"percent"} by default.
#' @param text_x vector containing the x co-ordiantes for the plot labels. Set
#'   to \code{NULL} by default to place labels in the center of the gates.
#' @param text_y vector containing the x co-ordiantes for the plot labels. Set
#'   to \code{NULL} by default to place labels in the center of the gates.
#' @param text_font integer [1,2,3,4] passed to \code{text} to alter the font,
#'   set to \code{2} by default for a bold font.
#' @param text_size numeric character expansion used to control the size of the
#'   text in the labels, set to \code{0.8} by default. See \code{?text} for
#'   details.
#' @param text_col specify text colour in label for each gate, defaults to
#'   \code{"black"} for all gates.
#' @param box_alpha numeric [0,1] controls the transparency of the background, set
#'   to \code{0.6} by default.
#'
#' @return add a boxed text label to cyto_plot.
#'
#' @importFrom flowCore Subset parameters
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @seealso \code{\link{cyto_plot_label,flowFrame,rectangleGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,polygonGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,list-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,filters-method}}
#'
#' @export
setMethod(cyto_plot_label,
  signature = c("flowFrame", "ellipsoidGate"),
  definition = function(x, 
                        gates, 
                        channels, 
                        text = NA, 
                        stat = NA, 
                        text_x = NA, 
                        text_y = NA, 
                        text_font = 2, 
                        text_size = 0.8,
                        text_col = "black", 
                        box_alpha = 0.6) {

    # Assign x to fr
    fr <- x

    # Channels needed to position label
    if (missing(channels)) {
      stop("Supply the name(s) of the fluorescent channels used to construct the plot.")
    }

    # Only count and percent supported
    if(!stat %in% c("count","percent")){
      stop("Only count and percent statistics are supported for 2D plots containing a polygonGate.")
    }
    
    # Missing text
    if (is.na(text) & !is.na(stat)) {
      message(paste("No text supplied for labels - labels will show", stat, "only."))
    }
    
    # Calculate statistic
    if(stat == "count"){
      st <- BiocGenerics::nrow(flowCore::Subset(fr, gates))
    }else if(stat == "percent"){
      # Total events
      events <- nrow(fr)
      
      # Population events - percentages
      cnt <- BiocGenerics::nrow(flowCore::Subset(fr, gates))
      prcnt <- round(cnt / events, 4)
      st <- sprintf("%.2f %%", 100 * prcnt)
    }

    # Check supplied channels & gate channels
    chans <- parameters(gates)

    if (!all(chans %in% channels)) {
      stop("Supplied channels do not match that of the supplied gate.")
    } else {
      if (is.na(text_x) & is.na(text_y)) {
        text_x <- gates@mean[channels[1]]
        text_y <- gates@mean[channels[2]]
      }
    }

    # Add labels
    if(!is.na(text) & !is.na(stat)){
      boxed.labels(x = text_x, y = text_y, labels = paste(text, st, sep = "\n"), border = FALSE, font = text_font, col = text_col, alpha.bg = box_alpha, cex = text_size)
    }else if(!is.na(text) & is.na(stat)){
      boxed.labels(x = text_x, y = text_y, labels = text, border = FALSE, font = text_font, col = text_col, alpha.bg = box_alpha, cex = text_size)
    }else if(is.na(text) & !is.na(stat)){
      boxed.labels(x = text_x, y = text_y, labels = st, border = FALSE, font = text_font, col = text_col, alpha.bg = box_alpha, cex = text_size)
    }
    
  }
)

#' Add boxed text labels to cyto_plot - list Method
#'
#' \code{cyto_plot_label} takes on a \code{flowFrame} object, population name
#' \code{text}, \code{channels} and a gate object to construct a text label for
#' the plot with the population name and frequency.
#'
#' @param x a \code{\link[flowCore:flowFrame-class]{flowFrame}} gated in the
#'   existing plot.
#' @param gates an object of class \code{"list"} containing objects of class
#'   \code{\link[flowCore:rectangleGate-class]{rectangleGate}},
#'   \code{\link[flowCore:polygonGate-class]{polygonGate}} or
#'   \code{\link[flowCore:ellipsoidGate-class]{ellipsoidGate}}.
#' @param trans object of class
#'   \code{\link[flowCore:transformList-class]{transformList}} or
#'   \code{\link[flowWorkspace]{transformerList}} generated by
#'   \code{\link[flowCore:logicleTransform]{estimateLogicle}} which was used to
#'   transform the fluorescent channels of the supplied flowFrame.
#' @param channels a vector indicating the fluorescent channel(s) to be used for
#'   gating.
#' @param text the name of the gated population, set to NA by default to only
#'   include percent in labels.
#' @param stat indicates the type of statistic to include in the label, can be
#'   either \code{"percent"}, \code{"count"}, \code{"median"}, \code{"mean"},
#'   \code{"mode"} or \code{"geo mean"}. \code{stat} is set to \code{"percent"}
#'   by default. Statistics for fluorescent intensity are calculated for the
#'   entire distribution. Only count and percent statistics are supported for 2D
#'   plots.
#' @param text_x vector containing the x co-ordiantes for the plot labels. Set
#'   to \code{NULL} by default to place labels in the center of the gates.
#' @param text_y vector containing the x co-ordiantes for the plot labels. Set
#'   to \code{NULL} by default to place labels in the center of the gates.
#' @param text_font integer [1,2,3,4] passed to \code{text} to alter the font,
#'   set to \code{2} by default for a bold font.
#' @param text_size numeric character expansion used to control the size of the
#'   text in the labels, set to \code{0.8} by default. See \code{?text} for
#'   details.
#' @param text_col specify text colour in label for each gate, defaults to
#'   \code{"black"} for all gates.
#' @param box_alpha numeric [0,1] controls the transparency of the background, set
#'   to \code{0.6} by default.
#'
#' @return add a boxed text label to cyto_plot.
#'
#' @importFrom flowCore Subset parameters
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @seealso \code{\link{cyto_plot_label,flowFrame,rectangleGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,polygonGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,ellipsoidGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,filters-method}}
#'
#' @export
setMethod(cyto_plot_label,
  signature = c("flowFrame", "list"),
  definition = function(x, 
                        gates, 
                        trans = NULL,
                        channels, 
                        text = NA, 
                        stat = NA, 
                        text_x = NA, 
                        text_y = NA, 
                        text_font = 2, 
                        text_size = 0.8,
                        text_col = "black", 
                        box_alpha = 0.6) {


    # Make calls to cyto_plot_label
    mapply(function(gate, text, text_font, text_col, text_size, box_alpha) {
      cyto_plot_label(x = x, trans = trans, gates = gate, channels = channels, text = text, stat = stat, text_font = text_font, text_col = text_col, text_size = text_size, box_alpha = box_alpha)
    }, gates, text, text_font, text_col, text_size, box_alpha)
  }
)

#' Add boxed text labels to cyto_plot - filters Method
#'
#' \code{cyto_plot_label} takes on a \code{flowFrame} object, population name
#' \code{text}, \code{channels} and a gate object to construct a text label for
#' the plot with the population name and frequency.
#'
#' @param x a \code{\link[flowCore:flowFrame-class]{flowFrame}} gated in the
#'   existing plot.
#' @param gates an object of class \code{\link[flowCore:filters-class]{filters}}
#'   containing objects of class
#'   \code{\link[flowCore:rectangleGate-class]{rectangleGate}},
#'   \code{\link[flowCore:polygonGate-class]{polygonGate}} or
#'   \code{\link[flowCore:ellipsoidGate-class]{ellipsoidGate}}.
#' @param trans object of class
#'   \code{\link[flowCore:transformList-class]{transformList}} or
#'   \code{\link[flowWorkspace]{transformerList}} generated by
#'   \code{\link[flowCore:logicleTransform]{estimateLogicle}} which was used to
#'   transform the fluorescent channels of the supplied flowFrame.
#' @param channels a vector indicating the fluorescent channel(s) to be used for
#'   gating.
#' @param text the name of the gated population, set to NA by default to only
#'   include percent in labels.
#' @param stat indicates the type of statistic to include in the label, can be
#'   either \code{"percent"}, \code{"count"}, \code{"median"}, \code{"mean"},
#'   \code{"mode"} or \code{"geo mean"}. \code{stat} is set to \code{"percent"}
#'   by default. Statistics for fluorescent intensity are calculated for the
#'   entire distribution. Only count and percent statistics are supported for 2D
#'   plots.
#' @param text_x vector containing the x co-ordiantes for the plot labels. Set
#'   to \code{NULL} by default to place labels in the center of the gates.
#' @param text_y vector containing the x co-ordiantes for the plot labels. Set
#'   to \code{NULL} by default to place labels in the center of the gates.
#' @param text_font integer [1,2,3,4] passed to \code{text} to alter the font,
#'   set to \code{2} by default for a bold font.
#' @param text_size numeric character expansion used to control the size of the
#'   text in the labels, set to \code{0.8} by default. See \code{?text} for
#'   details.
#' @param text_col specify text colour in label for each gate, defaults to
#'   \code{"black"} for all gates.
#' @param box_alpha numeric [0,1] controls the transparency of the background, set
#'   to \code{0.6} by default.
#'
#' @return add a boxed text label to cyto_plot.
#'
#' @importFrom flowCore Subset parameters
#'
#' @author Dillon Hammill (Dillon.Hammill@anu.edu.au)
#'
#' @seealso \code{\link{cyto_plot_label,flowFrame,rectangleGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,polygonGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,ellipsoidGate-method}}
#' @seealso \code{\link{cyto_plot_label,flowFrame,list-method}}
#'
#' @export
setMethod(cyto_plot_label,
  signature = c("flowFrame", "filters"),
  definition = function(x,
                        gates, 
                        trans = NULL,
                        channels, 
                        text = NA, 
                        stat = NA, 
                        text_x = NA, 
                        text_y = NA, 
                        text_font = 2, 
                        text_size = 0.8,
                        text_col = "black", 
                        box_alpha = 0.6) {

    # Make calls to cyto_plot_label
    mapply(function(gate, text, text_font, text_col, text_size, box_alpha) {
      cyto_plot_label(x = x, trans = trans, gates = gate, channels = channels, text = text, stat = stat, text_font = text_font, text_col = text_col, text_size = text_size, box_alpha = box_alpha)
    }, gates, text, text_font, text_col, text_size, box_alpha)
  }
)
